### ISSUE TITLE
关于pod版本支持的小建议

### ISSUE THREAD

**Issue by MrBugDou** [liudiange/DGDownloadManager#2]
我看了下您的代码，是完全支持iOS8.0的呀，为啥要在podspec里指定ios,"9.0"呢，现在还是有很多应用要支持iOS8.0的呢。小小建议希望采纳。

**Comment by songhongkang** [comment]
哈哈，也没有几个类，可以自己再上传一遍~

**Comment by liudiange** [comment]
好的 ，等我有时间了加下，然后我在用swift重写一个swift版本的。谢谢！

**Comment by liudiange** [comment]
oc可以直接桥接的
