### ISSUE TITLE
遇到的问题

### ISSUE THREAD

**Issue by 553559555** [liudiange/DGDownloadManager#7]
1. 下载进度：目前只能拿到当前下载进度和速度，通过model.task.progress.completedUnitCount和self.model?.task.progress.totalUnitCount获取不到当前下载大小和文件大小。
2. 我下载的MP4文件，在下载完成后获取的location文件类型是一个.tmp，并且我去沙盒里面找不到文件

**Comment by liudiange** [comment]
1.我有告诉一个地方去获取下载进度
2.沙河里面有的 ，思路是 下找一个临时文件进行存储，然后在下载完成之后进行移动到真实的文件目录
